version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: helicon
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      # @see https://github.com/docker-library/postgres/issues/263#issuecomment-280504406
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    ports:
      - 5433:5432
    platform: linux/x86_64

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: helicon
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - mysql-data:/var/lib/mysql:rw
    ports:
      - 3307:3306
    platform: linux/x86_64


volumes:
  postgres-data:
  mysql-data:
